// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJTZMTwVzaqxJ-Daaue_r_AR7XjOkWOd4',
    appId: '1:1080110098436:web:3f06dca25e2b34c24e2d51',
    messagingSenderId: '1080110098436',
    projectId: 'biker-1ec21',
    authDomain: 'biker-1ec21.firebaseapp.com',
    storageBucket: 'biker-1ec21.firebasestorage.app',
    measurementId: 'G-X441Z4K3LJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVmwLw3CqwDV4TbBmziThiQ9utJ7UKcOY',
    appId: '1:1080110098436:android:c2564feede55ff954e2d51',
    messagingSenderId: '1080110098436',
    projectId: 'biker-1ec21',
    storageBucket: 'biker-1ec21.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBW6e0_lU5_9MxUZaVdOhobiJZBdzE3MNs',
    appId: '1:1080110098436:ios:75e40f243cd932e04e2d51',
    messagingSenderId: '1080110098436',
    projectId: 'biker-1ec21',
    storageBucket: 'biker-1ec21.firebasestorage.app',
    iosBundleId: 'com.example.bikar',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBW6e0_lU5_9MxUZaVdOhobiJZBdzE3MNs',
    appId: '1:1080110098436:ios:75e40f243cd932e04e2d51',
    messagingSenderId: '1080110098436',
    projectId: 'biker-1ec21',
    storageBucket: 'biker-1ec21.firebasestorage.app',
    iosBundleId: 'com.example.bikar',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBJTZMTwVzaqxJ-Daaue_r_AR7XjOkWOd4',
    appId: '1:1080110098436:web:8ebc56beb9c6068d4e2d51',
    messagingSenderId: '1080110098436',
    projectId: 'biker-1ec21',
    authDomain: 'biker-1ec21.firebaseapp.com',
    storageBucket: 'biker-1ec21.firebasestorage.app',
    measurementId: 'G-2KS2Z09ZY5',
  );
}
